version: "3"
tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from room.proto"
    cmds:
      - mkdir -p pb && protoc -I proto proto/room.proto --go_out=./pb --go_opt=paths=source_relative --go-grpc_out=./pb --go-grpc_opt=paths=source_relative